package com.threemoji.threemoji;

import java.util.Random;

public class NameGenerator {
    static String[] adjectives =
            {"abandoned", "able", "absolute", "academic", "acclaimed", "accurate", "aching",
             "acidic", "acrobatic", "adorable", "babyish", "back", "bad", "baggy", "bare", "barren",
             "basic", "beautiful", "belated", "beloved", "calm", "candid", "canine", "capital",
             "carefree", "careful", "careless", "caring", "cautious", "cavernous", "charming",
             "damaged", "damp", "dangerous", "dapper", "daring", "dark", "darling", "dazzling",
             "dead", "deadly", "deafening", "dear", "dearest", "each", "eager", "early", "earnest",
             "easy", "easygoing", "ecstatic", "edible", "educated", "fabulous", "failing", "faint",
             "fair", "faithful", "fake", "familiar", "famous", "fancy", "fantastic", "far",
             "faraway", "farflung", "faroff", "gaseous", "general", "generous", "gentle", "genuine",
             "giant", "giddy", "gigantic", "hairy", "half", "handmade", "handsome", "handy",
             "happy", "hard", "icky", "icy", "ideal", "identical", "idiotic", "idle", "idolized",
             "ignorant", "ill", "illegal", "jaded", "jagged", "jampacked", "keen", "lame", "lanky",
             "large", "last", "lasting", "late", "lavish", "lawful", "mad", "madeup", "majestic",
             "major", "male", "mammoth", "married", "marvelous", "naive", "narrow", "nasty",
             "natural", "naughty", "obedient", "obese", "oblong", "oblong", "obvious", "oily",
             "palatable", "pale", "paltry", "parallel", "parched", "partial", "past", "pastel",
             "peaceful", "peppery", "perfect", "perfumed", "quaint", "qualified", "radiant",
             "ragged", "rapid", "rare", "rash", "raw", "recent", "reckless", "sad", "safe", "salty",
             "same", "sandy", "sane", "sarcastic", "sardonic", "satisfied", "scaly", "scarce",
             "scared", "scary", "scented", "scholarly", "scornful", "scratchy", "scrawny", "second",
             "secondary", "secret", "selfish", "talkative", "tall", "tame", "tan", "tangible",
             "tart", "tasty", "tattered", "taut", "tedious", "teeming", "ugly", "ultimate",
             "unaware", "uncommon", "unequaled", "vacant", "vague", "vain", "valid", "wan",
             "warlike", "warm", "warped", "wary", "wasteful", "watchful", "watery", "wavy",
             "yawning", "yearly", "zany", "false", "active", "actual", "adept", "admirable",
             "admired", "adorable", "adored", "advanced", "afraid", "aged", "best", "better",
             "bewitched", "big", "bitesized", "bitter", "black", "cheap", "cheerful", "cheery",
             "chief", "chilly", "chubby", "circular", "classic", "clean", "clear", "clearcut",
             "clever", "close", "closed", "decent", "decimal", "decisive", "deep", "defensive",
             "defiant", "deficient", "definite", "delayed", "delicious", "elaborate", "elastic",
             "elated", "elderly", "electric", "elegant", "fast", "fat", "fatal", "fatherly",
             "favorable", "favorite", "fearful", "fearless", "feisty", "feline", "female",
             "feminine", "few", "fickle", "gifted", "giving", "glamorous", "glaring", "glass",
             "gleaming", "gleeful", "harmful", "harmless", "harsh", "hasty", "hateful", "haunting",
             "illfated", "imaginary", "immediate", "immense", "jaunty", "jealous", "jittery", "key",
             "kind", "lazy", "leading", "leafy", "lean", "left", "legal", "light", "masculine",
             "massive", "mature", "meager", "mealy", "mean", "measly", "meaty", "medical",
             "mediocre", "nautical", "near", "neat", "necessary", "needy", "odd", "oddball",
             "offbeat", "offensive", "official", "old", "periodic", "perky", "personal",
             "pertinent", "pesky", "petty", "phony", "physical", "piercing", "pink", "pitiful",
             "plain", "quarterly", "ready", "real", "realistic", "red", "regal", "regular",
             "separate", "serene", "serious", "several", "severe", "shabby", "shadowy", "shady",
             "shallow", "shameful", "shameless", "sharp", "shiny", "shocked", "shocking", "shoddy",
             "short", "shortterm", "showy", "shrill", "shy", "sick", "silent", "silky", "tempting",
             "tender", "tense", "tepid", "terrible", "terrific", "testy", "thankful", "that",
             "these", "uneven", "unfit", "unfolded", "unhappy", "unhealthy", "uniform", "unique",
             "valuable", "vapid", "variable", "vast", "velvety", "weak", "wealthy", "weary",
             "webbed", "wee", "weekly", "weepy", "weighty", "weird", "welcome", "yellow", "zealous",
             "agile", "agitated", "agonizing", "agreeable", "ajar", "alarmed", "alarming", "alert",
             "alienated", "alive", "all", "bland", "blank", "blaring", "bleak", "blind", "blissful",
             "blond", "blue", "blushing", "cloudy", "clueless", "clumsy", "cluttered", "coarse",
             "cold", "colorful", "colorless", "colossal", "common", "competent", "complete",
             "delirious", "demanding", "dense", "dental", "dependent", "deserted", "detailed",
             "devoted", "different", "eminent", "emotional", "empty", "enchanted", "energetic",
             "enormous", "filthy", "fine", "finished", "firm", "first", "firsthand", "fitting",
             "fixed", "flaky", "flashy", "flat", "flawed", "flawless", "gloomy", "glorious",
             "glossy", "glum", "golden", "good", "gorgeous", "graceful", "healthy", "heartfelt",
             "hearty", "heavenly", "heavy", "hefty", "helpful", "helpless", "impartial",
             "imperfect", "impish", "impolite", "important", "joint", "jolly", "jovial", "kindly",
             "likable", "likely", "limited", "limp", "limping", "linear", "lined", "liquid",
             "medium", "meek", "mellow", "melodic", "memorable", "menacing", "merry", "messy",
             "metallic", "mild", "negative", "neglected", "nervous", "new", "only", "open",
             "optimal", "opulent", "plaintive", "plastic", "playful", "pleasant", "pleased",
             "pleasing", "plump", "plush", "pointed", "pointless", "poised", "polished", "polite",
             "political", "queasy", "querulous", "reliable", "relieved", "remote", "repentant",
             "required", "silly", "silver", "similar", "simple", "sinful", "single", "sizzling",
             "skeletal", "skinny", "sleepy", "slight", "slim", "slimy", "slippery", "slow",
             "slushy", "small", "smart", "smoggy", "smooth", "smug", "snappy", "snarling", "sneaky",
             "sniveling", "snoopy", "thick", "thin", "third", "thirsty", "this", "thorny",
             "thorough", "those", "united", "unkempt", "unknown", "unlawful", "unlined", "unlucky",
             "unnatural", "venerated", "vengeful", "vibrant", "vicious", "welllit", "wellmade",
             "welloff", "welltodo", "wellworn", "wet", "which", "whimsical", "whirlwind",
             "whispered", "yellowish", "zesty", "amazing", "ambitious", "ample", "amused",
             "amusing", "anchored", "ancient", "angelic", "angry", "anguished", "animated",
             "annual", "another", "antique", "bogus", "boiling", "bold", "bony", "boring", "bossy",
             "both", "bouncy", "bountiful", "bowed", "complex", "composed", "concerned", "concrete",
             "confused", "conscious", "constant", "content", "cooked", "cool", "difficult",
             "digital", "diligent", "dim", "dimpled", "dimwitted", "direct", "discrete", "disloyal",
             "dismal", "enraged", "entire", "envious", "equal", "essential", "esteemed", "ethical",
             "euphoric", "flimsy", "flippant", "flowery", "fluffy", "fluid", "flustered", "focused",
             "fond", "foolhardy", "foolish", "forceful", "forked", "formal", "forsaken", "gracious",
             "grand", "grandiose", "granular", "grateful", "grave", "gray", "great", "greedy",
             "green", "hidden", "hideous", "high", "highlevel", "hilarious", "hoarse", "hollow",
             "homely", "impure", "inborn", "indelible", "indolent", "infamous", "infantile",
             "joyful", "joyous", "jubilant", "klutzy", "knobby", "little", "live", "lively",
             "livid", "loathsome", "lone", "lonely", "long", "milky", "mindless", "miniature",
             "minor", "minty", "miserable", "miserly", "misguided", "misty", "mixed", "next",
             "nice", "nifty", "nimble", "nippy", "orange", "orderly", "ordinary", "organic",
             "ornate", "ornery", "poor", "popular", "portly", "posh", "positive", "possible",
             "potable", "powerful", "powerless", "practical", "precious", "present", "quick",
             "repulsive", "revolving", "rewarding", "rich", "right", "rigid", "ringed", "ripe",
             "sociable", "soft", "soggy", "solid", "somber", "some", "sore", "sorrowful", "soulful",
             "soupy", "sour", "spanish", "sparkling", "sparse", "specific", "speedy", "spherical",
             "spicy", "spiffy", "spirited", "spiteful", "splendid", "spotless", "spotted", "spry",
             "thrifty", "tidy", "tight", "timely", "tinted", "tiny", "tired", "torn", "total",
             "unripe", "unruly", "unselfish", "unsightly", "unsteady", "unsung", "untidy",
             "untimely", "untried", "vigilant", "vigorous", "violet", "white", "whole", "whopping",
             "wicked", "wide", "wideeyed", "wiggly", "wild", "willing", "wilted", "winding",
             "windy", "young", "zigzag", "anxious", "any", "apt", "arctic", "arid", "aromatic",
             "artistic", "ashamed", "assured", "athletic", "brave", "breakable", "brief", "bright",
             "brilliant", "brisk", "broken", "bronze", "brown", "bruised", "corny", "corrupt",
             "costly", "courteous", "crafty", "crazy", "creamy", "creative", "creepy", "criminal",
             "crisp", "dirty", "disguised", "dishonest", "dismal", "distant", "distant", "distinct",
             "distorted", "dizzy", "dopey", "downright", "dreary", "even", "evergreen", "every",
             "evil", "exalted", "excellent", "excitable", "exemplary", "exhausted", "fortunate",
             "fragrant", "frail", "frank", "frayed", "free", "french", "frequent", "fresh",
             "friendly", "frigid", "grim", "grimy", "gripping", "grizzled", "gross", "grotesque",
             "grouchy", "grounded", "honest", "honorable", "honored", "hopeful", "horrible", "hot",
             "huge", "inferior", "infinite", "informal", "innocent", "insecure", "insidious",
             "insistent", "judicious", "juicy", "jumbo", "knotty", "knowing", "longterm", "loose",
             "lopsided", "lost", "loud", "lovable", "lovely", "loving", "modern", "modest", "moist",
             "monstrous", "monthly", "moral", "mortified", "motherly", "nocturnal", "noisy",
             "nonstop", "normal", "notable", "noted", "original", "other", "our", "outgoing",
             "outlying", "precious", "pretty", "previous", "pricey", "prickly", "primary", "prime",
             "pristine", "private", "prize", "probable", "quiet", "roasted", "robust", "rosy",
             "rotating", "rotten", "rough", "round", "rowdy", "square", "squeaky", "squiggly",
             "stable", "staid", "stained", "stale", "standard", "starchy", "stark", "starry",
             "steel", "steep", "sticky", "stiff", "stingy", "stormy", "straight", "strange",
             "strict", "strident", "striking", "striped", "strong", "studious", "stunning", "tough",
             "tragic", "trained", "traumatic", "treasured", "tricky", "trifling", "trim", "untrue",
             "unused", "unusual", "unwelcome", "unwieldy", "unwilling", "unwitting", "unwritten",
             "upbeat", "violent", "virtual", "virtuous", "visible", "winged", "wiry", "wise",
             "witty", "wobbly", "woeful", "wonderful", "wooden", "woozy", "wordy", "worldly",
             "worn", "youthful", "attached", "attentive", "austere", "authentic", "automatic",
             "average", "aware", "awesome", "awful", "awkward", "bubbly", "bulky", "bumpy",
             "buoyant", "burly", "bustling", "busy", "buttery", "buzzing", "critical", "crooked",
             "crowded", "cruel", "crushing", "cuddly", "cultured", "curly", "curvy", "cute",
             "doting", "double", "downright", "drab", "drafty", "dramatic", "dreary", "droopy",
             "dry", "dual", "dull", "dutiful", "excited", "exciting", "exotic", "expensive",
             "expert", "frilly", "frivolous", "frizzy", "front", "frosty", "frozen", "frugal",
             "fruitful", "full", "fumbling", "funny", "fussy", "fuzzy", "growing", "growling",
             "grown", "grubby", "gruesome", "grumpy", "guilty", "gullible", "gummy", "humble",
             "humming", "humongous", "hungry", "hurtful", "husky", "intent", "internal", "intrepid",
             "ironclad", "itchy", "jumpy", "junior", "juvenile", "known", "kooky", "kosher", "low",
             "loyal", "lucky", "lumbering", "luminous", "lumpy", "lustrous", "luxurious", "muddy",
             "muffled", "mundane", "murky", "mushy", "musty", "muted", "novel", "noxious", "numb",
             "nutty", "oval", "overdue", "overjoyed", "profuse", "proper", "proud", "prudent",
             "punctual", "pungent", "puny", "pure", "purple", "pushy", "putrid", "puzzled",
             "puzzling", "quirky", "quixotic", "quizzical", "royal", "rubbery", "ruddy", "rude",
             "rundown", "runny", "rural", "rusty", "stupid", "sturdy", "stylish", "subdued",
             "subtle", "suburban", "sudden", "sugary", "sunny", "super", "superb", "superior",
             "surprised", "svelte", "sweaty", "sweet", "swift", "trivial", "troubled", "trusting",
             "trusty", "truthful", "tubby", "turbulent", "twin", "upright", "upset", "urban",
             "usable", "used", "useful", "useless", "utilized", "utter", "vital", "vivacious",
             "vivid", "worried", "worrisome", "worse", "worst", "worthless", "worthy", "wrathful",
             "wretched", "writhing", "wrong", "wry", "yummy", "true", "aliceblue", "aqua", "azure",
             "beige", "bisque", "black", "blue", "brown", "burlywood", "cadetblue", "chocolate",
             "coral", "cornsilk", "crimson", "cyan", "darkblue", "darkcyan", "darkgray",
             "darkgreen", "darkgrey", "darkkhaki", "darkred", "deeppink", "dimgray", "dimgrey",
             "firebrick", "fractal", "fuchsia", "gainsboro", "gold", "goldenrod", "gray", "green",
             "honeydew", "hotpink", "indianred", "indigo", "ivory", "khaki", "lavender",
             "lawngreen", "lightblue", "lightcyan", "lightgray", "lightgrey", "lightpink", "lime",
             "limegreen", "linen", "magenta", "maroon", "mintcream", "mistyrose", "moccasin",
             "navy", "navyblue", "oldlace", "olive", "olivedrab", "opaque", "orange", "orangered",
             "orchid", "palegreen", "peachpuff", "peru", "pink", "plum", "purple", "red",
             "rosybrown", "royalblue", "salmon", "seagreen", "seashell", "sienna", "silver",
             "skyblue", "slateblue", "slategray", "slategrey", "snow", "steelblue", "tan", "teal",
             "thistle", "tomato", "turquoise", "violet", "violetred", "wheat", "white", "yellow"};

    static String[] animals = {"aardvark", "aardwolf", "abalone", "acaciarat", "acouchi", "addax",
                               "adder", "adouri", "aegeancat", "agama", "agouti", "aidi",
                               "airedale", "akitainu", "albatross", "albino", "alleycat",
                               "alligator", "alpaca", "ambushbug", "ammonite", "amoeba",
                               "amphibian", "amphiuma", "anaconda", "anchovy", "andeancat",
                               "anemone", "angelfish", "angora", "anhinga", "ankole", "annelid",
                               "annelida", "anole", "ant", "antbear", "anteater", "antelope",
                               "antlion", "anura", "aoudad", "apatosaur", "ape", "aphid",
                               "appaloosa", "aracari", "arachnid", "arawana", "arcticfox", "argali",
                               "argusfish", "arkshell", "armadillo", "armedcrab", "armyant",
                               "armyworm", "arrowana", "arrowcrab", "arrowworm", "aruanas",
                               "asianlion", "asp", "ass", "astarte", "atlasmoth", "auk", "auklet",
                               "aurochs", "avians", "avocet", "axisdeer", "axolotl", "ayeaye",
                               "aztecant", "azurevase", "babirusa", "baboon", "bactrian", "badger",
                               "bagworm", "baiji", "baldeagle", "bandicoot", "banteng", "barasinga",
                               "barb", "barbet", "barnacle", "barnowl", "barracuda", "basenji",
                               "basil", "basilisk", "bass", "bat", "bats", "beagle", "bear",
                               "beauceron", "beaver", "bedbug", "bee", "beetle", "bellfrog",
                               "bellsnake", "betafish", "bettong", "bighorn", "bilby", "billygoat",
                               "binturong", "bird", "bison", "bittern", "blackbear", "blackbird",
                               "blackbuck", "blackfish", "blackfly", "blacklab", "blesbok",
                               "blobfish", "blowfish", "bluebird", "bluefish", "bluegill",
                               "bluejay", "blueshark", "bluet", "bluewhale", "boa", "boar",
                               "bobcat", "bobolink", "bobwhite", "bongo", "bonobo", "booby",
                               "borer", "borzoi", "boto", "boubou", "boutu", "bovine", "brant",
                               "bream", "bronco", "brownbear", "buck", "budgie", "bufeo", "buffalo",
                               "bug", "bull", "bullfrog", "bumblebee", "bunny", "bunting", "burro",
                               "bushbaby", "bustard", "butterfly", "buzzard", "caecilian", "caiman",
                               "calf", "camel", "canary", "canine", "capybara", "caracal",
                               "cardinal", "caribou", "carp", "cassowary", "cat", "catbird",
                               "catfish", "cats", "cattle", "caudata", "cavy", "centipede", "cero",
                               "chafer", "chameleon", "chamois", "cheetah", "chick", "chickadee",
                               "chicken", "chihuahua", "chipmunk", "chital", "chrysalis", "cicada",
                               "cirriped", "civet", "clam", "clingfish", "clumber", "coati", "cob",
                               "cobra", "cock", "cockatiel", "cockatoo", "cockroach", "cod",
                               "collie", "colt", "comet", "conch", "condor", "coney", "conure",
                               "cony", "coot", "cooter", "copepod", "coqui", "coral", "cormorant",
                               "cornsnake", "cougar", "cow", "cowbird", "cowrie", "coyote", "coypu",
                               "crab", "crane", "cranefly", "crayfish", "creature", "cricket",
                               "crocodile", "crossbill", "crow", "cub", "cuckoo", "cur", "curassow",
                               "curlew", "cuscus", "cusimanse", "cutworm", "cygnet", "dachshund",
                               "dairycow", "dalmatian", "damselfly", "dartfrog", "dassie",
                               "dassierat", "deer", "deermouse", "degu", "degus", "devilfish",
                               "dikdik", "dikkops", "dingo", "dinosaur", "dipper", "discus", "dodo",
                               "dodobird", "doe", "dog", "dogfish", "dolphin", "donkey", "dorado",
                               "dore", "dorking", "dormouse", "dotterel", "dove", "dowitcher",
                               "dragon", "dragonfly", "drake", "drever", "dromedary", "drongo",
                               "duck", "duckling", "dugong", "duiker", "dunlin", "dunnart", "eagle",
                               "earthworm", "earwig", "echidna", "eel", "eeve", "eft", "egg",
                               "egret", "eider", "eland", "elephant", "elk", "elkhound", "elver",
                               "emu", "equine", "erin", "ermine", "erne", "eskimodog", "esok",
                               "ewe", "eyas", "eyra", "fairyfly", "falcon", "fantail", "fanworms",
                               "fawn", "feline", "fennecfox", "ferret", "finch", "finwhale",
                               "fireant", "firecrest", "firefly", "fish", "flamingo", "flatfish",
                               "flea", "flee", "flicker", "flies", "flounder", "fluke", "fly",
                               "flyingfox", "foal", "fossa", "fowl", "fox", "foxhound", "frog",
                               "frogmouth", "fruitbat", "fruitfly", "fugu", "fulmar", "furseal",
                               "gadwall", "galago", "galah", "gallinule", "gander", "gannet", "gar",
                               "garpike", "gaur", "gavial", "gazelle", "gecko", "geese", "gelada",
                               "gelding", "gemsbok", "gemsbuck", "genet", "gerbil", "gerenuk",
                               "gharial", "gibbon", "giraffe", "glassfrog", "globefish", "glowworm",
                               "gnat", "gnu", "goa", "goat", "godwit", "goitered", "goldeneye",
                               "goldfinch", "goldfish", "gonolek", "goose", "goosefish", "gopher",
                               "goral", "gorilla", "goshawk", "gosling", "gourami", "grackle",
                               "grayfox", "grayling", "graywolf", "greatdane", "grebe", "grison",
                               "grosbeak", "groundhog", "grouper", "grouse", "grub", "grunion",
                               "guanaco", "guillemot", "guineapig", "gull", "guppy", "gypsymoth",
                               "gyrfalcon", "hackee", "haddock", "hagfish", "hake", "halcyon",
                               "halibut", "halicore", "hamadryad", "hamadryas", "hammerkop",
                               "hamster", "hapuka", "hapuku", "hare", "harpseal", "harrier", "hart",
                               "hawk", "hedgehog", "heifer", "hen", "herald", "heron", "herring",
                               "hind", "hoatzin", "hog", "hogget", "hoiho", "hoki", "honeybee",
                               "hoopoe", "hornbill", "hornet", "hornshark", "horse", "horsefly",
                               "hound", "housefly", "hoverfly", "huemul", "huia", "human", "husky",
                               "hydra", "hyena", "hyrax", "ibex", "ibis", "ibisbill", "icefish",
                               "ichidna", "iggypops", "iguana", "iguanodon", "imago", "impala",
                               "incatern", "inchworm", "indiancow", "indri", "inganue", "insect",
                               "isopod", "ivorygull", "izuthrush", "jabiru", "jackal", "jaeger",
                               "jaguar", "javalina", "jay", "jellyfish", "jenny", "jerboa", "joey",
                               "johndory", "junco", "junebug", "kagu", "kakapo", "kakarikis",
                               "kangaroo", "karakul", "katydid", "kawala", "kestrel", "kid",
                               "killdeer", "killifish", "kingbird", "kinglet", "kingsnake",
                               "kinkajou", "kiskadee", "kite", "kitfox", "kitten", "kittiwake",
                               "kitty", "kiwi", "koala", "koalabear", "kob", "koi", "koodoo",
                               "kouprey", "krill", "kudu", "kusimanse", "lacewing", "ladybird",
                               "ladybug", "lamb", "lamprey", "langur", "lark", "larva", "lcont",
                               "leafbird", "leafwing", "leech", "lemming", "lemur", "leopard",
                               "leveret", "lhasaapso", "lice", "liger", "limpet", "limpkin", "ling",
                               "lion", "lionfish", "lizard", "llama", "lobo", "lobster", "locust",
                               "longhorn", "longspur", "loon", "lorikeet", "loris", "louse",
                               "lovebird", "lowchen", "lunamoth", "lungfish", "lynx", "macaque",
                               "macaw", "macropod", "maggot", "magpie", "maiasaura", "malamute",
                               "mallard", "mamba", "mammal", "mammoth", "manatee", "mandrill",
                               "mangabey", "manta", "mantaray", "mantid", "mantis", "mantisray",
                               "manxcat", "mara", "marabou", "mare", "marlin", "marmoset", "marmot",
                               "marten", "martin", "mastiff", "mastodon", "mayfly", "mealworm",
                               "meerkat", "merganser", "merlin", "mice", "midge", "milksnake",
                               "millipede", "minibeast", "mink", "minnow", "mite", "moa", "mole",
                               "mollies", "mollusk", "molly", "monarch", "mongoose", "mongrel",
                               "monkey", "moorhen", "moose", "moray", "morayeel", "morpho",
                               "mosasaur", "mosquito", "moth", "motmot", "mouflon", "mouse",
                               "mousebird", "mudpuppy", "mule", "mullet", "muntjac", "murrelet",
                               "muskox", "muskrat", "mussaurus", "mussel", "mustang", "mutt",
                               "myna", "mynah", "nabarlek", "nag", "naga", "nagapies", "nandine",
                               "nandoo", "nandu", "narwhal", "narwhale", "nauplius", "nautilus",
                               "nematode", "nene", "neontetra", "nerka", "newt", "nighthawk",
                               "nightjar", "nilgai", "noctilio", "noctule", "noddy", "norwayrat",
                               "numbat", "nuthatch", "nutria", "nyala", "nymph", "ocelot",
                               "octopus", "okapi", "olingo", "olm", "opossum", "orangutan", "orca",
                               "oriole", "oryx", "osprey", "ostracod", "ostrich", "otter",
                               "ovenbird", "owl", "ox", "oxen", "oxpecker", "oyster", "pachyderm",
                               "panda", "pangolin", "panther", "paperwasp", "papillon", "parakeet",
                               "parrot", "partridge", "peacock", "peafowl", "peccary", "pekingese",
                               "pelican", "penguin", "perch", "pewee", "phalarope", "pheasant",
                               "phoebe", "phoenix", "pig", "pigeon", "piglet", "pika", "pike",
                               "pilchard", "pinniped", "pintail", "pipit", "piranha", "pitbull",
                               "pittabird", "plankton", "platypus", "plover", "polarbear",
                               "polecat", "polliwog", "polyp", "pony", "pooch", "poodle",
                               "porcupine", "porpoise", "possum", "prawn", "primate", "pronghorn",
                               "ptarmigan", "puffer", "puffin", "pug", "pullet", "puma", "pupa",
                               "pupfish", "puppy", "pussycat", "pygmy", "python", "quagga",
                               "quahog", "quail", "queenant", "queenbee", "quelea", "quetzal",
                               "quillback", "quokka", "quoll", "rabbit", "raccoon", "racer",
                               "ragfish", "rail", "ram", "raptors", "rasbora", "rat", "ratfish",
                               "rattail", "raven", "ray", "redhead", "redpoll", "redstart",
                               "reindeer", "reptile", "reynard", "rhea", "rhino", "ringworm",
                               "roach", "roan", "robberfly", "robin", "rockrat", "rodent",
                               "roebuck", "roller", "rook", "rooster", "sable", "saiga", "salmon",
                               "sambar", "sandpiper", "sapsucker", "sardine", "sawfish", "scallop",
                               "scarab", "scaup", "schnauzer", "scorpion", "scoter", "screamer",
                               "seabird", "seagull", "seahog", "seahorse", "seal", "sealion",
                               "seamonkey", "seaslug", "seaurchin", "seriema", "serpent", "serval",
                               "shark", "sheep", "sheldrake", "shelduck", "shibainu", "shihtzu",
                               "shorebird", "shoveler", "shrew", "shrike", "shrimp", "siamang",
                               "sifaka", "silkworm", "silverfox", "siskin", "skimmer", "skink",
                               "skipper", "skua", "skunk", "skylark", "sloth", "slothbear", "slug",
                               "smelts", "smew", "snail", "snake", "snipe", "snowdog", "snowgeese",
                               "snowyowl", "solenodon", "solitaire", "songbird", "sora", "sow",
                               "spadefoot", "sparrow", "sphinx", "spider", "spiketail", "sponge",
                               "spoonbill", "springbok", "squab", "squamata", "squeaker", "squid",
                               "squirrel", "stag", "stallion", "starfish", "starling", "steed",
                               "steer", "stilt", "stingray", "stinkbug", "stinkpot", "stoat",
                               "stonefly", "stork", "stud", "sturgeon", "sunbear", "sunfish",
                               "swallow", "swan", "swellfish", "swift", "swordfish", "tadpole",
                               "tahr", "takin", "tamarin", "tanager", "tapaculo", "tapeworm",
                               "tapir", "tarantula", "tarpan", "tarsier", "taruca", "tattler",
                               "tayra", "teal", "tegus", "teledu", "tench", "tenrec", "termite",
                               "tern", "terrapin", "terrier", "thrasher", "thrip", "thrush",
                               "thylacine", "tick", "tiger", "tigermoth", "tilefish", "tinamou",
                               "titi", "titmouse", "toad", "toadfish", "topi", "tortoise", "toucan",
                               "towhee", "tragopan", "trex", "trogon", "trout", "tsetsefly",
                               "tuatara", "tuna", "turaco", "turkey", "turnstone", "turtle",
                               "uakari", "ugandakob", "umbrette", "unau", "ungulate", "unicorn",
                               "upupa", "urchin", "urial", "urson", "urubu", "urus", "urutu",
                               "urva", "vaquita", "veery", "verdin", "vervet", "vicuna", "viper",
                               "viperfish", "vireo", "vixen", "vole", "volvox", "vulture",
                               "wallaby", "wallaroo", "walleye", "walrus", "warbler", "warthog",
                               "wasp", "waterbuck", "waterbug", "waterdogs", "watussi", "waxwing",
                               "weasel", "weevil", "whale", "whapuku", "whelp", "whimbrel",
                               "whippet", "whiteeye", "whooper", "widgeon", "wildcat", "willet",
                               "wireworm", "wisent", "wolf", "wolverine", "wombat", "woodborer",
                               "woodchuck", "woodcock", "worm", "wrasse", "wreckfish", "wren",
                               "wryneck", "wyvern", "xanclomys", "xantus", "xeme", "xenarthra",
                               "xenops", "xenopus", "xenurine", "xerus", "xiphias", "xoni",
                               "xrayfish", "xraytetra", "yaffle", "yak", "yapok", "yardant",
                               "yearling", "yeti", "ynambu", "yucker", "zander", "zebra",
                               "zebradove", "zebrafish", "zebu", "zenaida", "zeren", "zopilote",
                               "zorilla"};

    static Random rand = new Random();

    public static String getName() {
        String adjective = adjectives[rand.nextInt(adjectives.length)];
        String animal = animals[rand.nextInt(animals.length)];
        return capitalize(adjective) + " " + capitalize(animal);
    }

    private static String capitalize(final String line) {
        return Character.toUpperCase(line.charAt(0)) + line.substring(1);
    }
}
